# Generated by Django 3.0.7 on 2020-07-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_movie_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.FloatField()),
                ('cantidad', models.FloatField()),
                ('categoria', models.CharField(max_length=150)),
                ('caducidad', models.DateField()),
            ],
            options={
                'db_table': 'alimentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsientosOcupados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columna', models.IntegerField()),
                ('fila', models.IntegerField()),
            ],
            options={
                'db_table': 'asientos_ocupados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(max_length=100)),
                ('nacimiento', models.DateField()),
                ('apellido', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50, unique=True)),
                ('costo', models.FloatField()),
            ],
            options={
                'db_table': 'entradas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('duration', models.IntegerField()),
                ('reparto', models.TextField()),
                ('showing', models.IntegerField()),
                ('director', models.CharField(max_length=120)),
                ('genre', models.CharField(max_length=120)),
                ('language', models.CharField(max_length=120)),
                ('synopsis', models.TextField()),
                ('thumbnail', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'main_movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecciones',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('inicio', models.TimeField()),
                ('asientos_vendidos', models.FloatField()),
            ],
            options={
                'db_table': 'proyecciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('asientos_totales', models.PositiveIntegerField()),
                ('filas', models.PositiveIntegerField()),
                ('columnas', models.PositiveIntegerField()),
                ('number_3d', models.IntegerField(db_column='3d')),
                ('vip', models.IntegerField()),
            ],
            options={
                'db_table': 'salas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('serial', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('monto_total', models.FloatField()),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
